language: julia

julia:
# - 1.2
  - 1.3

codecov: true

coveralls: true

os:
  - linux
# - osx
# - windows


after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
